# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: salamane <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/30 15:57:35 by salamane          #+#    #+#              #
#    Updated: 2022/08/30 15:57:40 by salamane         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=megaphone
GXX=g++
CXXFLAGS=-Wall -Wextra -Werror -o
SRCS=megaphone.cpp

$(NAME):
	$(GXX) $(SRCS) $(CXXFLAGS) $(NAME)
all:$(NAME)

fclean:
	rm -rf $(NAME)
re:fclean all