NAME=BraiiiiiiinnnzzzZ
GXX=g++
CXXFLAGS=-Wall -Wextra -Werror -o
SRCS=main.cpp Zombie.cpp randomChump.cpp newZombie.cpp

$(NAME):
	$(GXX) $(SRCS) $(CXXFLAGS) $(NAME)
all:$(NAME)

fclean:
	rm -rf $(NAME)
re:fclean all